import 'styles/globals.css';
import type { Metadata } from 'next';
import { Archivo_Narrow } from 'next/font/google';
import Header from 'components/shared/Header';
import Footer from 'components/shared/Footer';
import { Credit } from 'components/shared/Credit';
import { Providers } from 'modules/providers';

const archivoNarrow = Archivo_Narrow({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    // const [isModalOpen] = useAtom(modalAtom);
    // const router = useRouter();

    // useEffect(() => {
    //     const handler = () => {
    //         setModal(false);
    //     };

    //     router.events.on('routeChangeComplete', handler);

    //     return () => {
    //         router.events.off('routeChangeComplete', handler);
    //     };
    // }, []);

    return (
        <html lang="en">
            <body className={archivoNarrow.className}>
                <Providers>
                    <Header />
                    <main>{children}</main>
                    <Footer />
                    <Credit />
                </Providers>
            </body>
        </html>
    );
}
